#define T_KEY_GO                           1
#define T_KEY_CREATE                       2
#define T_KEY_DATABASE                     3
#define T_IDENTIFIER                       4
#define T_STRING                           5
#define T_KEY_INITIALIZE                   6
#define T_KEY_USE                          7
#define T_KEY_WITH                         8
#define T_KEY_KEY                          9
#define T_KEY_USING                       10
#define T_KEY_ENCODING                    11
#define T_KEY_DROP                        12
#define T_KEY_VACUUM                      13
#define T_KEY_ANALYZE                     14
#define T_KEY_INDEXES                     15
#define T_KEY_ON                          16
#define T_KEY_OBJECT                      17
#define T_KEY_OPEN_SQUARE_BRACKET         18
#define T_KEY_CLOSE_SQUARE_BRACKET        19
#define T_KEY_TYPE                        20
#define T_KEY_TYPES                       21
#define T_KEY_BEGIN                       22
#define T_KEY_TRANSACTION                 23
#define T_KEY_COMMIT                      24
#define T_KEY_ABORT                       25
#define T_KEY_MULTIPLE                    26
#define T_KEY_RANGE                       27
#define T_KEY_OBJECTS                     28
#define T_KEY_SINGLE                      29
#define T_KEY_MONAD                       30
#define T_KEY_HAVING                      31
#define T_KEY_UNIQUE                      32
#define T_KEY_FIRST                       33
#define T_KEY_MONADS                      34
#define T_KEY_AND                         35
#define T_KEY_LAST                        36
#define T_KEY_WITHOUT                     37
#define T_KEY_COLON                       38
#define T_KEY_SEMICOLON                   39
#define T_KEY_LIST                        40
#define T_KEY_OF                          41
#define T_KEY_INTEGER                     42
#define T_KEY_STRING                      43
#define T_KEY_ASCII                       44
#define T_KEY_ID_D                        45
#define T_KEY_SET                         46
#define T_KEY_INDEX                       47
#define T_KEY_IF                          48
#define T_KEY_NOT                         49
#define T_KEY_EXISTS                      50
#define T_KEY_FROM                        51
#define T_KEY_OPEN_BRACKET                52
#define T_INTEGER                         53
#define T_KEY_CLOSE_BRACKET               54
#define T_KEY_DEFAULT                     55
#define T_KEY_COMPUTED                    56
#define T_KEY_UPDATE                      57
#define T_KEY_REMOVE                      58
#define T_KEY_ADD                         59
#define T_KEY_INSERT                      60
#define T_KEY_DELETE                      61
#define T_KEY_GET                         62
#define T_KEY_CALCULATION                 63
#define T_KEY_UNION                       64
#define T_KEY_DIFFERENCE                  65
#define T_KEY_INTERSECT                   66
#define T_KEY_SELECT                      67
#define T_KEY_SETS                        68
#define T_KEY_ALL                         69
#define T_KEY_REPLACE                     70
#define T_KEY_COMMA                       71
#define T_KEY_EQUALS                      72
#define T_KEY_OPEN_BRACE                  73
#define T_KEY_CLOSE_BRACE                 74
#define T_KEY_ENUMERATION                 75
#define T_KEY_ENUM                        76
#define T_KEY_DASH                        77
#define T_KEY_NIL                         78
#define T_KEY_SEGMENT                     79
#define T_KEY_IN                          80
#define T_KEY_FOCUS                       81
#define T_KEY_MAX                         82
#define T_KEY_MAX_M                       83
#define T_KEY_FEATURE                     84
#define T_KEY_RETURNING                   85
#define T_KEY_FULL                        86
#define T_KEY_SHEAF                       87
#define T_KEY_FLAT                        88
#define T_KEY_WHERE                       89
#define T_KEY_AT                          90
#define T_KEY_AGGREGATE                   91
#define T_KEY_FEATURES                    92
#define T_KEY_MIN                         93
#define T_KEY_SUM                         94
#define T_KEY_COUNT                       95
#define T_KEY_STAR                        96
#define T_KEY_ENUMERATIONS                97
#define T_KEY_CONSTANTS                   98
#define T_KEY_MIN_M                       99
#define T_KEY_ASSIGN                     100
#define T_KEY_ID_DS                      101
#define T_KEY_BY                         102
#define T_KEY_QUIT                       103
#define T_KEY_EXCLAMATION                104
#define T_KEY_OR                         105
#define T_KEY_NOTEXIST                   106
#define T_KEY_NOTEXISTS                  107
#define T_KEY_AS                         108
#define T_MARK                           109
#define T_KEY_NORETRIEVE                 110
#define T_KEY_RETRIEVE                   111
#define T_KEY_PART_OF                    112
#define T_KEY_STARTS_IN                  113
#define T_KEY_OVERLAP                    114
#define T_KEY_UNIVERSE                   115
#define T_KEY_SUBSTRATE                  116
#define T_KEY_LESS_THAN                  117
#define T_KEY_GREATER_THAN               118
#define T_KEY_NOT_EQUAL                  119
#define T_KEY_LESS_THAN_OR_EQUAL         120
#define T_KEY_GREATER_THAN_OR_EQUAL      121
#define T_KEY_TILDE                      122
#define T_KEY_NOT_TILDE                  123
#define T_KEY_HAS                        124
#define T_KEY_DOT                        125
#define T_KEY_UNORDERED_GROUP            126
#define T_KEY_OPT_GAP                    127
#define T_KEY_GAP                        128
#define T_KEY_POWER                      129
#define T_KEY_BETWEEN                    130
