//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Emdros {

public class BookcaseHit : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BookcaseHit(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BookcaseHit obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BookcaseHit() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csemdrosPINVOKE.delete_BookcaseHit(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_int_fast64_t m_bookcase_fm {
    set {
      csemdrosPINVOKE.BookcaseHit_m_bookcase_fm_set(swigCPtr, SWIGTYPE_p_int_fast64_t.getCPtr(value));
      if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_int_fast64_t ret = new SWIGTYPE_p_int_fast64_t(csemdrosPINVOKE.BookcaseHit_m_bookcase_fm_get(swigCPtr), true);
      if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_int_fast64_t m_bookcase_lm {
    set {
      csemdrosPINVOKE.BookcaseHit_m_bookcase_lm_set(swigCPtr, SWIGTYPE_p_int_fast64_t.getCPtr(value));
      if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_int_fast64_t ret = new SWIGTYPE_p_int_fast64_t(csemdrosPINVOKE.BookcaseHit_m_bookcase_lm_get(swigCPtr), true);
      if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_int_fast64_t m_hit_fm {
    set {
      csemdrosPINVOKE.BookcaseHit_m_hit_fm_set(swigCPtr, SWIGTYPE_p_int_fast64_t.getCPtr(value));
      if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_int_fast64_t ret = new SWIGTYPE_p_int_fast64_t(csemdrosPINVOKE.BookcaseHit_m_hit_fm_get(swigCPtr), true);
      if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public BookcaseHit(SWIGTYPE_p_int_fast64_t bookcase_fm, SWIGTYPE_p_int_fast64_t bookcase_lm, SWIGTYPE_p_int_fast64_t hit_fm) : this(csemdrosPINVOKE.new_BookcaseHit__SWIG_0(SWIGTYPE_p_int_fast64_t.getCPtr(bookcase_fm), SWIGTYPE_p_int_fast64_t.getCPtr(bookcase_lm), SWIGTYPE_p_int_fast64_t.getCPtr(hit_fm)), true) {
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public BookcaseHit(BookcaseHit other) : this(csemdrosPINVOKE.new_BookcaseHit__SWIG_1(BookcaseHit.getCPtr(other)), true) {
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
