//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Emdros {

public enum eBackendKind {
  kBackendNone = 0,
  kPostgreSQL = 1,
  kMySQL = 2,
  kSQLite3 = 4,
  kBPT = 5,
  kBPT2 = 6
}

}
