//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Emdros {

public enum eCharsets {
  kCSASCII,
  kCSISO_8859_1,
  kCSISO_8859_8,
  kCSUTF8,
  kCSISO_8859_2,
  kCSISO_8859_3,
  kCSISO_8859_4,
  kCSISO_8859_5,
  kCSISO_8859_6,
  kCSISO_8859_7,
  kCSISO_8859_9,
  kCSISO_8859_10,
  kCSISO_8859_13,
  kCSISO_8859_14,
  kCSISO_8859_15,
  kCSISO_8859_16
}

}
