//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Emdros {

public class FlatStrawConstIterator : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FlatStrawConstIterator(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FlatStrawConstIterator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FlatStrawConstIterator() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csemdrosPINVOKE.delete_FlatStrawConstIterator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public FlatStrawConstIterator() : this(csemdrosPINVOKE.new_FlatStrawConstIterator__SWIG_0(), true) {
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public FlatStrawConstIterator(FlatStraw pMotherFlatStraw) : this(csemdrosPINVOKE.new_FlatStrawConstIterator__SWIG_1(FlatStraw.getCPtr(pMotherFlatStraw)), true) {
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public FlatStrawConstIterator(FlatStrawConstIterator other) : this(csemdrosPINVOKE.new_FlatStrawConstIterator__SWIG_2(FlatStrawConstIterator.getCPtr(other)), true) {
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool hasNext() {
    bool ret = csemdrosPINVOKE.FlatStrawConstIterator_hasNext(swigCPtr);
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public MatchedObject next() {
    global::System.IntPtr cPtr = csemdrosPINVOKE.FlatStrawConstIterator_next(swigCPtr);
    MatchedObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new MatchedObject(cPtr, false);
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public MatchedObject current() {
    global::System.IntPtr cPtr = csemdrosPINVOKE.FlatStrawConstIterator_current(swigCPtr);
    MatchedObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new MatchedObject(cPtr, false);
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
