//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Emdros {

public class RenderObjects : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RenderObjects(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RenderObjects obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~RenderObjects() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csemdrosPINVOKE.delete_RenderObjects(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public RenderObjects(EmdrosEnv pEnv, string db_name, SWIGTYPE_p_JSONValue pFetchInfo, string stylesheet) : this(csemdrosPINVOKE.new_RenderObjects__SWIG_0(EmdrosEnv.getCPtr(pEnv), db_name, SWIGTYPE_p_JSONValue.getCPtr(pFetchInfo), stylesheet), true) {
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public RenderObjects(EmdrosEnv pEnv, string db_name, SWIGTYPE_p_JSONValue pFetchInfo) : this(csemdrosPINVOKE.new_RenderObjects__SWIG_1(EmdrosEnv.getCPtr(pEnv), db_name, SWIGTYPE_p_JSONValue.getCPtr(pFetchInfo)), true) {
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public RenderObjects(EmdrosEnv pEnv, string db_name, string JSON_stylesheet, string stylesheet) : this(csemdrosPINVOKE.new_RenderObjects__SWIG_2(EmdrosEnv.getCPtr(pEnv), db_name, JSON_stylesheet, stylesheet), true) {
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public RenderObjects(EmdrosEnv pEnv, string db_name, string JSON_stylesheet) : this(csemdrosPINVOKE.new_RenderObjects__SWIG_3(EmdrosEnv.getCPtr(pEnv), db_name, JSON_stylesheet), true) {
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool process(SWIGTYPE_p_int_fast64_t fm, SWIGTYPE_p_int_fast64_t lm) {
    bool ret = csemdrosPINVOKE.RenderObjects_process(swigCPtr, SWIGTYPE_p_int_fast64_t.getCPtr(fm), SWIGTYPE_p_int_fast64_t.getCPtr(lm));
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getDocument() {
    string ret = csemdrosPINVOKE.RenderObjects_getDocument(swigCPtr);
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void clean() {
    csemdrosPINVOKE.RenderObjects_clean(swigCPtr);
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public string getError() {
    string ret = csemdrosPINVOKE.RenderObjects_getError(swigCPtr);
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
