//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Emdros {

public class Sheaf : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Sheaf(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Sheaf obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Sheaf() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csemdrosPINVOKE.delete_Sheaf(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public Sheaf(Sheaf other) : this(csemdrosPINVOKE.new_Sheaf(Sheaf.getCPtr(other)), true) {
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isFail() {
    bool ret = csemdrosPINVOKE.Sheaf_isFail(swigCPtr);
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SheafIterator iterator() {
    SheafIterator ret = new SheafIterator(csemdrosPINVOKE.Sheaf_iterator(swigCPtr), true);
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SheafConstIterator const_iterator() {
    SheafConstIterator ret = new SheafConstIterator(csemdrosPINVOKE.Sheaf_const_iterator(swigCPtr), true);
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void printConsole(EMdFOutput pOut) {
    csemdrosPINVOKE.Sheaf_printConsole(swigCPtr, EMdFOutput.getCPtr(pOut));
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public void printXML(EMdFOutput pOut) {
    csemdrosPINVOKE.Sheaf_printXML(swigCPtr, EMdFOutput.getCPtr(pOut));
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void printSheafStartConsole(EMdFOutput pOut) {
    csemdrosPINVOKE.Sheaf_printSheafStartConsole(EMdFOutput.getCPtr(pOut));
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void printSheafStartXML(EMdFOutput pOut) {
    csemdrosPINVOKE.Sheaf_printSheafStartXML(EMdFOutput.getCPtr(pOut));
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void printSheafEndXML(EMdFOutput pOut) {
    csemdrosPINVOKE.Sheaf_printSheafEndXML(EMdFOutput.getCPtr(pOut));
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void printDTD(EMdFOutput pOut) {
    csemdrosPINVOKE.Sheaf_printDTD(EMdFOutput.getCPtr(pOut));
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public void printJSON(EMdFOutput pOut) {
    csemdrosPINVOKE.Sheaf_printJSON(swigCPtr, EMdFOutput.getCPtr(pOut));
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void printSheafStartJSON(EMdFOutput pOut, bool hasLOS) {
    csemdrosPINVOKE.Sheaf_printSheafStartJSON(EMdFOutput.getCPtr(pOut), hasLOS);
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void printSheafEndJSON(EMdFOutput pOut, bool hasLOS) {
    csemdrosPINVOKE.Sheaf_printSheafEndJSON(EMdFOutput.getCPtr(pOut), hasLOS);
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_int_fast64_t countObjects(bool bUseOnlyFocusObjects) {
    SWIGTYPE_p_int_fast64_t ret = new SWIGTYPE_p_int_fast64_t(csemdrosPINVOKE.Sheaf_countObjects(swigCPtr, bUseOnlyFocusObjects), true);
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_int_fast64_t countObjectsFromObjectType(string object_type_name, bool bUseOnlyFocusObjects) {
    SWIGTYPE_p_int_fast64_t ret = new SWIGTYPE_p_int_fast64_t(csemdrosPINVOKE.Sheaf_countObjectsFromObjectType(swigCPtr, object_type_name, bUseOnlyFocusObjects), true);
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_int_fast64_t countStraws() {
    SWIGTYPE_p_int_fast64_t ret = new SWIGTYPE_p_int_fast64_t(csemdrosPINVOKE.Sheaf_countStraws(swigCPtr), true);
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void getSOM(SetOfMonads som, bool bUseOnlyFocusObjects) {
    csemdrosPINVOKE.Sheaf_getSOM__SWIG_0(swigCPtr, SetOfMonads.getCPtr(som), bUseOnlyFocusObjects);
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public void harvestMarks(SWIGTYPE_p_String2SOMMap result, bool bUseSingleMarks) {
    csemdrosPINVOKE.Sheaf_harvestMarks(swigCPtr, SWIGTYPE_p_String2SOMMap.getCPtr(result), bUseSingleMarks);
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
  }

  public SetOfMonads getSOM(bool bUseOnlyFocusObjects) {
    SetOfMonads ret = new SetOfMonads(csemdrosPINVOKE.Sheaf_getSOM__SWIG_1(swigCPtr, bUseOnlyFocusObjects), true);
    if (csemdrosPINVOKE.SWIGPendingException.Pending) throw csemdrosPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
