//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Emdros {

public enum TableColumnType {
  kTCString,
  kTCInteger,
  kTCID_D,
  kTCMonad_m,
  kTCBool,
  kTCEnum,
  kTCListOfInteger,
  kTCListOfID_D,
  kTCListOfEnum,
  kTCSetOfMonads
}

}
