.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH EMDROS 5 "January 16, 2019"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
emdros \- text database engine for analyzed or annotated text
.SH SYNOPSIS
.B mql
.RI [ options ] 
.br
.B eqtc
.RI [ options ] 
.br
.B eqtu
.RI [ options ] 
.br
.B mqldump
.RI [ options ] 
.br
.B emdftry
.RI [ options ] 
.br
.B mqltry
.RI [ options ] 
.br
.B mqllingtry
.RI [ options ] 
.br
.SH DESCRIPTION
This manual page briefly documents the Emdros engine and some of its
command-line programs.

\fBEmdros\fP is a text database engine for analyzed or annotated text.
It is especially well suited to storing and retrieving linguistic
analyses of text.  Emdros comes with a powerful query language, called
MQL, which allows the user to ask relevant questions of the data.

Emdros is useful especially in corpus linguistics, but also in areas
such as annotation of text, text mining, and publishing.

A handful of utilities are provided which ease Emdros database
administration. These are described briefly below, and also on their
man pages.

.B mql(1) 
is the main Emdros program.  It is an interface to the MQL language.

.B eqtc(1), eqtu(1)
are front-ends for querying Emdros databases, giving human-readable
results.  The eqtc(1) program is for command-line use, while eqtu(1)
is for graphical usage.

.B mqldump(1) 
is a utility for dumping (parts of) an Emdros database into MQL.

.B emdftry(1) 
is a testing program which exercises the Emdros EMdF library, telling
the user if anything is wrong.

.B mqltry(1) 
is a testing program which exercises the Emdros MQL library, telling
the user if anything is wrong.

.B mqllingtry(1) 
is a testing program which exercises the Emdros MQL library in a small
toy linguistic application, telling the user if anything is wrong.

.B sqlite3_emdros(1)
are the native SQL interfaces to SQLite (2 and 3) for Emdros databases.



.SH OPTIONS
These programs mostly follow the usual GNU command line syntax, with
long options starting with two dashes (`-').

A summary of options is included below.
For a complete description, see the man pages.
.TP
.B \-\-help
Show summary of options.
.TP
.B \-V, \-\-version
Show version of program.
.SH SEE ALSO
.BR mql(1),
.BR eqtc(1),
.BR eqtu(1),
.BR mqldump(1),
.BR emdftry(1),
.BR mqltry(1),
.BR sqlite3_emdros(1),
.BR mqllingtry(1),
.BR sqlite3_emdros(1),
.br

See also the Emdros website: <http://emdros.org/> and especially the
Programmer's Reference Guide: <http://emdros.org/progref/current/>.

.SH AUTHOR
The Emdros programs, and this manual page, were written by Ulrik
Sandborg-Petersen <ulrikp@emdros.org>.
