#define T_TEMPLATELANG_KEY_ID_D                         1
#define T_TEMPLATELANG_KEY_FIRSTMONAD                   2
#define T_TEMPLATELANG_KEY_FEATURE                      3
#define T_TEMPLATELANG_KEY_SPACE                        4
#define T_TEMPLATELANG_INTEGER                          5
#define T_TEMPLATELANG_KEY_BB_CLOSE                     6
#define T_TEMPLATELANG_KEY_FEATUREJSONMANGLE            7
#define T_TEMPLATELANG_KEY_FEATURENOMANGLE              8
#define T_TEMPLATELANG_KEY_DBNAME                       9
#define T_TEMPLATELANG_KEY_ATTRIB                      10
#define T_TEMPLATELANG_IDENTIFIER                      11
#define T_TEMPLATELANG_KEY_ATTRIB_NOMANGLE             12
#define T_TEMPLATELANG_KEY_COPYATTRIBS                 13
#define T_TEMPLATELANG_KEY_COUNTER                     14
#define T_TEMPLATELANG_STRING                          15
#define T_TEMPLATELANG_KEY_BARE_FORMAT                 16
#define T_TEMPLATELANG_KEY_SETCOUNTER                  17
#define T_TEMPLATELANG_KEY_BARE_VAR                    18
#define T_TEMPLATELANG_KEY_INCCOUNTER                  19
#define T_TEMPLATELANG_KEY_DECCOUNTER                  20
#define T_TEMPLATELANG_KEY_LISTEMIT                    21
#define T_TEMPLATELANG_KEY_LISTCLEAR                   22
#define T_TEMPLATELANG_KEY_NAMEDSETEMIT                23
#define T_TEMPLATELANG_KEY_NAMEDSETCLEAR               24
#define T_TEMPLATELANG_KEY_DICTLOOKUP                  25
#define T_TEMPLATELANG_KEY_BARE_FEATURE                26
#define T_TEMPLATELANG_KEY_BARE_FEATURENOMANGLE        27
#define T_TEMPLATELANG_KEY_BARE_VARNOMANGLE            28
#define T_TEMPLATELANG_KEY_BARE_COUNTER                29
#define T_TEMPLATELANG_KEY_SETNIXING_ALL               30
#define T_TEMPLATELANG_KEY_SETNIXING_DOC               31
#define T_TEMPLATELANG_KEY_SETNIXING_OFF               32
#define T_TEMPLATELANG_KEY_IF_FEATUREEQUAL             33
#define T_TEMPLATELANG_KEY_IF_VAREQUAL                 34
#define T_TEMPLATELANG_KEY_IF_LISTEMPTY                35
#define T_TEMPLATELANG_KEY_IF_NAMEDSETEMPTY            36
#define T_TEMPLATELANG_KEY_IF_HASATTRIB                37
#define T_TEMPLATELANG_KEY_IF_ATTRIBEQUAL              38
#define T_TEMPLATELANG_KEY_ENDIF                       39
#define T_TEMPLATELANG_KEY_ELSE                        40
#define T_TEMPLATELANG_KEY_LISTAPPENDBEGIN             41
#define T_TEMPLATELANG_KEY_LISTAPPENDEND               42
#define T_TEMPLATELANG_KEY_NAMEDSETADD                 43
#define T_TEMPLATELANG_KEY_NAMEDSETADDEND              44
#define T_TEMPLATELANG_KEY_NAMEDSETREMOVE              45
#define T_TEMPLATELANG_KEY_NAMEDSETREMOVEEND           46
#define T_TEMPLATELANG_KEY_SETVAR                      47
#define T_TEMPLATELANG_KEY_SETVAREND                   48
#define T_TEMPLATELANG_KEY_EMITVAR                     49
#define T_TEMPLATELANG_CHAR                            50
#define T_TEMPLATELANG_KEY_NEWLINE                     51
